# Generated by Django 4.1 on 2022-09-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Information'},
        ),
    ]
