# Generated by Django 4.1 on 2022-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_options_alter_contactinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
            ],
        ),
    ]
