# Generated by Django 4.1 on 2022-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
