# Generated by Django 4.1 on 2022-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_socialmediahandles_delete_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediahandles',
            name='link',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
