# Generated by Django 4.1 on 2022-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_socialmediahandles_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediahandles',
            name='icon',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
