# Generated by Django 4.1 on 2022-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_reply_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='PraiseMedia', max_length=100),
        ),
    ]
