# Generated by Django 4.1 on 2022-09-07 21:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section_two',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
