# Generated by Django 4.1 on 2022-09-08 08:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_section_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section_one',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
