# Generated by Django 4.1 on 2022-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_section_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section_one',
            field=models.TextField(),
        ),
    ]
