# Generated by Django 4.1 on 2022-09-08 08:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_section_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section_three',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
