# Generated by Django 4.1 on 2022-09-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_section_three'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='section_two',
        ),
    ]
