# Generated by Django 4.1 on 2022-09-08 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_section_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section_two',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
