# Generated by Django 4.1 on 2022-09-08 10:47

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_section_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section_three',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='section_two',
            field=django_quill.fields.QuillField(),
        ),
    ]
