# Generated by Django 4.1 on 2022-09-08 11:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_section_three_alter_post_section_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='section_three',
        ),
        migrations.AlterField(
            model_name='post',
            name='section_two',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
