# Generated by Django 3.2.12 on 2022-03-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='Interest',
            new_name='interest',
        ),
    ]
