# Generated by Django 3.2.12 on 2022-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_interest_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
