# Generated by Django 3.2.12 on 2022-03-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_services_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
