# Generated by Django 4.1 on 2022-09-08 19:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_services_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
