# Generated by Django 3.2.12 on 2022-03-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
