# Generated by Django 3.2.12 on 2022-03-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20220311_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(),
        ),
    ]
